name: Build and Deploy

on:
  push:
    branches:
      - staging
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install dependencies for React app
      - name: Install dependencies
        run: |
          cd hr-client
          npm install

      # Build React app
      - name: Build React app
        run: |
          cd hr-client
          npm run build

      # Build the project from the main branch
      - name: Build Project from main branch
        run: |
          git fetch origin main
          git checkout main
          cd hr-client
          npm run build

      # Deploy to Staging or Release Server based on the branch
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          STAGING_SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
          RELEASE_SERVER_IP: ${{ secrets.RELEASE_SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Determine target server based on the branch
          if [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            TARGET_SERVER_IP=$STAGING_SERVER_IP
            echo "Branch is staging, targeting staging server ($TARGET_SERVER_IP)"
          elif [[ "$GITHUB_REF" == "refs/heads/release" ]]; then
            TARGET_SERVER_IP=$RELEASE_SERVER_IP
            echo "Branch is release, targeting release server ($TARGET_SERVER_IP)"
          else
            echo "Branch is neither staging nor release, no server selected"
            exit 0
          fi
 
          TARGET_SERVER_PATH="/var/www/html/HRMS/hr-client/"

          # Test SSH connection
          echo "Testing SSH connection to $SERVER_USER@$TARGET_SERVER_IP"
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$TARGET_SERVER_IP "echo 'SSH connection successful'"

          # Deploy the build folder to the appropriate server
          echo "Deploying to $SERVER_USER@$TARGET_SERVER_IP:$TARGET_SERVER_PATH"
          scp -o StrictHostKeyChecking=no -r hr-client/build/* $SERVER_USER@$TARGET_SERVER_IP:$TARGET_SERVER_PATH