name: Build and Deploy

on:
  push:
    branches:
      - staging
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Install dependencies for React app
      - name: Install dependencies
        run: |
          cd hr-client
          npm install

      # Build the project from the main branch
      - name: Build Project from main branch
        run: |
          cd hr-client
          npm run build

      # Deploy to Staging or Release Server based on the branch
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          STAGING_SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
          RELEASE_SERVER_IP: ${{ secrets.RELEASE_SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
          # Determine target server
          if [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            TARGET_SERVER_IP=$STAGING_SERVER_IP
            echo "Targeting staging server ($TARGET_SERVER_IP)"
          elif [[ "$GITHUB_REF" == "refs/heads/release" ]]; then
            TARGET_SERVER_IP=$RELEASE_SERVER_IP
            echo "Targeting release server ($TARGET_SERVER_IP)"
          else
            exit 0
          fi
      
          # Define paths
          SOURCE_PATH="hr-client/dist"
          TARGET_PATH="/var/www/html/HRMS/hr-client"
      
          # Verify source files
          echo "Source files:"
          ls -la $SOURCE_PATH
      
          # Verify and prepare target directory
          echo "Preparing target directory..."
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$TARGET_SERVER_IP \
            "mkdir -p $TARGET_PATH && chmod -R 755 $TARGET_PATH"
      
          # Deploy files (using proper path syntax)
          echo "Deploying files..."
          scp -o StrictHostKeyChecking=no -r $SOURCE_PATH/* $SERVER_USER@$TARGET_SERVER_IP:$TARGET_PATH/
      
          # Verify deployment
          echo "Verifying deployment..."
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$TARGET_SERVER_IP \
            "ls -la $TARGET_PATH"