name: Build and Deploy

on:
  push:
    branches:
      - staging
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project from the main branch
      - name: Build Project
        run: |
          git fetch origin main
          git checkout main
          npm run build

      # Deploy to Staging or Release Server based on the branch
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          STAGING_SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
          RELEASE_SERVER_IP: ${{ secrets.RELEASE_SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          # Ensure the SSH private key is available for the server connection
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Determine target server based on the branch
          if [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
            TARGET_SERVER_IP=$STAGING_SERVER_IP
            TARGET_SERVER_PATH="/path/to/staging/server/folder"
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            TARGET_SERVER_IP=$RELEASE_SERVER_IP
            TARGET_SERVER_PATH="/path/to/release/server/folder"
          fi

          # Deploy the build folder to the appropriate server
          echo "Deploying to $TARGET_SERVER_IP"
          scp -r dist/* $SERVER_USER@$TARGET_SERVER_IP:$TARGET_SERVER_PATH
