name: Build and Deploy

on:
  push:
    branches:
      - staging
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Install dependencies for React app
      - name: Install dependencies
        run: |
          cd hr-client
          npm install

      # Build the project from the main branch
      - name: Build Project from main branch
        run: |
          cd hr-client
          npm run build

      # Deploy to Staging or Release Server based on the branch
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          STAGING_SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
          RELEASE_SERVER_IP: ${{ secrets.RELEASE_SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Determine target server
          if [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            TARGET_SERVER_IP=$STAGING_SERVER_IP
            echo "Targeting staging server ($TARGET_SERVER_IP)"
          elif [[ "$GITHUB_REF" == "refs/heads/release" ]]; then
            TARGET_SERVER_IP=$RELEASE_SERVER_IP
            echo "Targeting release server ($TARGET_SERVER_IP)"
          else
            exit 0
          fi
      
          # Verify source files
          echo "Source files in hr-client/dist:"
          ls -la hr-client/dist/
      
          # Absolute path for scp command
          TARGET_PATH="/var/www/html/HRMS/hr-client"
      
          # Debug: Verify target directory exists and is writable
          echo "Verifying target directory permissions..."
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$TARGET_SERVER_IP \
            "ls -ld $TARGET_PATH && touch $TARGET_PATH/testfile && rm $TARGET_PATH/testfile"
          
          # Deploy using absolute paths and proper escaping
          echo "Deploying files..."
          scp -o StrictHostKeyChecking=no -rp hr-client/dist/* "$SERVER_USER@$TARGET_SERVER_IP:$TARGET_PATH/"
      
          # Verify deployment
          echo "Verifying deployed files..."
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$TARGET_SERVER_IP \
            "ls -la $TARGET_PATH"