name: Build and Deploy

on:
  push:
    branches:
      - staging
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies for React app
      - name: Install dependencies
        run: |
          cd hr-client
          npm install

      # Build React app
      - name: Build React app
        run: |
          cd hr-client
          npm run build

      # Build the project from the main branch
      - name: Build Project from main branch
        run: |
          git fetch origin main
          git checkout main
          cd hr-client
          npm run build

      # Deploy to Staging or Release Server based on the branch
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          STAGING_SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
          RELEASE_SERVER_IP: ${{ secrets.RELEASE_SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add SSH host to known_hosts to prevent "Host key verification failed"
          ssh-keyscan -H $STAGING_SERVER_IP >> ~/.ssh/known_hosts
          ssh-keyscan -H $RELEASE_SERVER_IP >> ~/.ssh/known_hosts
          
          # Determine target server based on the branch
          if [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
            TARGET_SERVER_IP=$STAGING_SERVER_IP
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            TARGET_SERVER_IP=$RELEASE_SERVER_IP
          fi
          
          TARGET_SERVER_PATH="/var/www/html/HRMS/hr-client/"

          # Deploy the build folder to the appropriate server
          ssh $SERVER_USER@$TARGET_SERVER_IP "mkdir -p $TARGET_SERVER_PATH"
          echo "Deploying to $TARGET_SERVER_IP:$TARGET_SERVER_PATH"
          scp -v -r hr-client/dist/* $SERVER_USER@$TARGET_SERVER_IP:$TARGET_SERVER_PATH
